apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
    - name: jenkins-agent-node
      image: registry.juvo.mobi/juvo/ops/jenkins-agent-node:v4
      command:
        - cat
      tty: true
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      resources:
        requests:
          ephemeral-storage: "2Gi"
          memory: "2Gi"
          cpu: "1"
        limits:
          ephemeral-storage: "4Gi"
          memory: "2Gi"
          cpu: "4"
    - name: dind-daemon
      image: docker:18.09.6-dind
      resources:
        requests:
          ephemeral-storage: "2Gi"
          memory: "2Gi"
          cpu: "250m"
        limits:
          ephemeral-storage: "8Gi"
          memory: "2Gi"
          cpu: "4"
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
      ports:
        - containerPort: 2375
  volumes:
    - name: docker-graph-storage
      emptyDir: {}
  imagePullSecrets:
    - name: juvo-registry