apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
    - name: node-build-agent
      image: 730036231311.dkr.ecr.us-west-2.amazonaws.com/juvo/ops/node-build-agent:0.1.2-SNAPSHOT
      command:
        - cat
      tty: true
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      resources:
        requests:
          ephemeral-storage: "1Gi"
          memory: "4Gi"
          cpu: "1"
        limits:
          ephemeral-storage: "1Gi"
          memory: "4Gi"
          cpu: "4"
    - name: dind-daemon
      image: docker:18.09.6-dind
      resources:
        requests:
          ephemeral-storage: "1Gi"
          memory: "256Mi"
          cpu: "250m"
        limits:
          ephemeral-storage: "4Gi"
          memory: "256Mi"
          cpu: "1"
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
      ports:
        - containerPort: 2375
  volumes:
    - name: docker-graph-storage
      emptyDir: {}