apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
    - name: jenkins-agent-node
      image: registry.juvo.mobi/juvo/ops/jenkins-agent-node:v4
      command:
        - cat
      tty: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      resources:
        requests:
          ephemeral-storage: "1Gi"
          memory: "1Gi"
          cpu: "1"
        limits:
          ephemeral-storage: "1Gi"
          memory: "1Gi"
          cpu: "4"
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
  imagePullSecrets:
    - name: juvo-registry