apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
      image: 'jenkins/jnlp-slave:alpine'
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
      resources:
        requests:
          ephemeral-storage: "250Mi"
          memory: "1Gi"
          cpu: "1"
        limits:
          ephemeral-storage: "4Gi"
          memory: "4Gi"
          cpu: "4"
    - name: jenkins-agent-ops
      image: 730036231311.dkr.ecr.us-west-2.amazonaws.com/juvo/ops/jenkins-agent-ops:v11
      command:
        - cat
      tty: true
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      resources:
        requests:
          ephemeral-storage: "250Mi"
          memory: "1Gi"
          cpu: "1"
        limits:
          ephemeral-storage: "4Gi"
          memory: "4Gi"
          cpu: "4"
    - name: dind-daemon
      image: docker:18.09.6-dind
      resources:
        requests:
          ephemeral-storage: "250Mi"
          memory: "256Mi"
          cpu: "250m"
        limits:
          ephemeral-storage: "4Gi"
          memory: "256Mi"
          cpu: "1"
      ports:
        - containerPort: 2375
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
  volumes:
    - name: docker-graph-storage
      emptyDir: {}