apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
    - name: ruby-build-agent
      image: 730036231311.dkr.ecr.us-west-2.amazonaws.com/juvo/ops/ruby-build-agent:0.1.3-SNAPSHOT
      command:
        - cat
      tty: true
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
    - name: dind-daemon
      image: docker:18.09.6-dind
      ports:
        - containerPort: 2375
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
  volumes:
    - name: docker-graph-storage
      emptyDir: {}