apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
    - name: jnlp
      image: 'jenkins/jnlp-slave:alpine'
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
      resources:
        requests:
          ephemeral-storage: "250Mi"
          memory: "1Gi"
          cpu: "1"
        limits:
          ephemeral-storage: "4Gi"
          memory: "8Gi"
          cpu: "4"
    - name: ruby-build-agent
      image: registry.juvo.mobi/juvo/ops/jenkins-agent-ruby:v11
      command:
        - cat
      tty: true
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      resources:
        requests:
          ephemeral-storage: "250Mi"
          memory: "1Gi"
          cpu: "1"
        limits:
          ephemeral-storage: "4Gi"
          memory: "2Gi"
          cpu: "4"
    - name: dind-daemon
      image: docker:18.09.6-dind
      resources:
        requests:
          ephemeral-storage: "250Mi"
          memory: "256Mi"
          cpu: "250m"
        limits:
          ephemeral-storage: "4Gi"
          memory: "2Gi"
          cpu: "1"
      ports:
        - containerPort: 2375
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
  volumes:
    - name: docker-graph-storage
      emptyDir: {}
  imagePullSecrets:
    - name: juvo-registry